# Site settings
title: "lilinji's Blog"
SEOTitle: lilinji的博客 | lilinji Blog
header-img: img/post-bg-unix-linux.jpg
username: lilinji
email: krystism@gmail.com
description: "About Linux、Openstack、Docker and Ceph "
keyword: "krystism, lilinji, 付广平, Fu Guangping, @lilinji, krystism Blog , lilinji的博客, lilinji Blog, 博客, 个人网站, 云计算, openstack, docker, 大数据, Hadoop, spark, ceph"
url: "http://lilinji.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
default_header_image: img/post-bg-universe.jpg

# SNS settings
RSS: true
weibo_username:     316378881
zhihu_username:     lilinji
github_username:    lilinji
twitter_username:  lilinji
#facebook_username:  lilinji

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# markdown: kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  hard_wrap: false

# Disqus settings
disqus_username: lilinji
# Duoshuo settings
#duoshuo_username: lilinji
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 2f615c9fc2d0100e5a6410b950fa688c

# Google Analytics
ga_track_id: 'UA-76500579-1'            # Format: UA-xxxxxx-xx
ga_domain: lilinji.github.io

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "专注于云计算、大数据和分布式，分享和讨论Openstack、Docker、Ceph以及Devops相关技术。"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "cnblog博客地址",
        href: "http://www.cnblogs.com/lilinji/"
    },{
        title: "麦子迈",
        href: "http://www.wzxue.com/"
    },{
        title: "酷壳",
        href: "http://coolshell.cn/"
    },{
        title: "陈沙克日志",
        href: "http://www.chenshake.com/"
    },{
        title: "世民谈云计算",
        href: "http://www.cnblogs.com/sammyliu/"
    },{
        title: "结构之法，算法之道",
        href: "http://blog.csdn.net/v_july_v"
    },{
    },{
        title: "阮一峰的网络日志",
        href: "http://www.ruanyifeng.com/"
    },{
        title: "Leetcode解题",
        href: "https://github.com/lilinji/leetcode"
    },{
        title: "依云's Blog",
        href: "http://blog.lilydjwg.me/"
    }
]
